### ISSUE TITLE
Links that don't open in a new tab

### ISSUE THREAD

**Issue by rachelaux** [AtHeartEngineering/pse_landingpage#34]
Testing links and most of them open in a new tab except for the social links in the footer 
<img width="1309" alt="Screen Shot 2022-06-10 at 9 47 23 AM" src="https://user-images.githubusercontent.com/81319667/173091341-5e27c259-b856-4ec8-bfa2-248cb8ddef0b.png">

and the icons next to project names
<img width="237" alt="Screen Shot 2022-06-10 at 9 47 41 AM" src="https://user-images.githubusercontent.com/81319667/173091394-30493b69-6ed7-4032-af3e-1cf6ba85c913.png">
.

**Comment by AtHeartEngineer** [comment]
https://github.com/AtHeartEngineering/pse_landingpage/commit/51d35d18e1d2b79e56bd86ab459662b175b71e37 Fixed, thanks!
